export const ALL_METRICS = [
  { id: "faturamento_bruto", label: "Faturamento Bruto" },
  { id: "gastos", label: "Gastos com anúncios" },
  { id: "roas", label: "ROAS" },
  { id: "lucro", label: "Lucro" },
  { id: "faturamento_liquido", label: "Faturamento Líquido" },
  { id: "vendas_pagamento", label: "Vendas por Pagamento" },
  { id: "vendas_pendentes", label: "Vendas Pendentes" },
  { id: "roi", label: "ROI" },
  { id: "margem", label: "Margem de Lucro" },
  { id: "reembolso_val", label: "Vendas Reembolsadas" },
  { id: "vendas_chargeback", label: "Vendas chargeback" },
  { id: "vendas_devolvidas", label: "Vendas devolvidas" },
  { id: "reembolso_perc", label: "Taxa de Reembolso" },
  { id: "chargeback", label: "Chargeback" },
  { id: "arpu", label: "ARPU" },
  { id: "imposto", label: "Imposto" },
  { id: "imposto_meta_ads", label: "Imposto Meta Ads" },
  { id: "imposto_total", label: "Imposto Total" },
  { id: "custos_produto", label: "Custos de Produto" },
  { id: "taxas", label: "Taxas" },
  { id: "vendas_produto", label: "Vendas por Produto" },
  { id: "faturamento_produto", label: "Faturamento por Produto" },
  { id: "vendas_fonte", label: "Vendas por Fonte" },
  { id: "vendas_src", label: "Vendas por Src" },
  { id: "vendas_posicionamento", label: "Vendas por Posicionamento" },
  { id: "vendas_pais", label: "Vendas por País" },
  { id: "taxa_aprovacao", label: "Taxa de Aprovação" },
  { id: "vendas_horario", label: "Vendas por Horário" },
  { id: "lucro_horario", label: "Lucro por Horário" },
  { id: "vendas_dia", label: "Vendas por Dia da Semana" },
  { id: "funil", label: "Funil de Conversão" },
  { id: "gastos_adicionais", label: "Gastos adicionais" },
  { id: "cpa", label: "CPA" },
  { id: "conversas", label: "Conversas" },
  { id: "custo_conversa", label: "Custo por Conversa" },
  { id: "leads", label: "Leads" },
  { id: "custo_lead", label: "Custo por Lead" },
  {
    id: "fat_inv_lucro_hora",
    label: "Faturamento x Investimento x Lucro por Hora",
  },
];
